name: street-mapper

services:
  app:
    image: oven/bun:alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "bun install && bun run dev --host --port 5000"
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/street_mapper
    depends_on:
      - db

  db:
    image: mysql:8.4
    restart: on-failure:5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=street_mapper
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
