name: street-mapper

services:
  app:
    image: oven/bun:alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "bun install && bun run dev --host --port 5000"
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?connection_limit=10
    depends_on:
      - db

  db:
    image: postgis/postgis:17-3.5-alpine
    restart: on-failure:5
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
